// topics
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ'
export const FETCH_TOPICS_SUC = 'FETCH_TOPICS_SUC'
export const FETCH_TOPICS_ERR = 'FETCH_TOPICS_ERR'
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA'
export const TOGGLE_NO_MORE_DATA_STATE = 'TOGGLE_NO_MORE_DATA_STATE'
export const TOGGLE_ERROR_DATA_STATE = 'TOGGLE_ERROR_DATA_STATE'
export const TOGGLE_ISFETCHING_STATE = 'TOGGLE_ISFETCHING_STATE'

// info
export const FETCH_INFO_REQ = 'FETCH_TOPIC_REQ'
export const FETCH_INFO_SUC = 'FETCH_TOPIC_SUC'
export const FETCH_INFO_ERR = 'FETCH_TOPIC_ERR'