// topics
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ'
export const FETCH_TOPICS_SUC = 'FETCH_TOPICS_SUC'
export const FETCH_TOPICS_ERR = 'FETCH_TOPICS_ERR'
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA'
export const TOGGLE_NO_MORE_DATA_STATE = 'TOGGLE_NO_MORE_DATA_STATE'
export const TOGGLE_ERROR_DATA_STATE = 'TOGGLE_ERROR_DATA_STATE'
export const TOGGLE_ISFETCHING_STATE = 'TOGGLE_ISFETCHING_STATE'

// login
export const FETCH_USER_REQ = 'FETCH_USER_REQ'
export const FETCH_USER_SUC = 'FETCH_USER_SUC'
export const FETCH_USER_ERR = 'FETCH_USER_ERR'
export const TOGGLE_SNACK_SHOW = 'TOGGLE_SNACK_SHOW'
export const TOGGLE_SNACK_STATE = 'TOGGLE_SNACK_STATE'
export const DEFINE_SNACK_MSG = 'DEFINE_SNACK_MSG'
export const COMMIT_USERINFO = 'COMMIT_USERINFO'
export const LOGOUT = 'LOGOUT'

// bottom nav
export const HANDLE_CHANGE = 'HANDLE_CHANGE'

// -----
// info page
export const FETCH_INFO_REQ = 'FETCH_INFO_REQ'
export const FETCH_INFO_SUC = 'FETCH_INFO_SUC'
export const FETCH_INFO_ERR = 'FETCH_INFO_ERR'
export const COMMIT_ID = 'COMMIT_ID'
export const TOGGLE_INFO_PAGE_DISPLAY = 'TOGGLE_INFO_PAGE_DISPLAY'

// replies page
export const SHOW_REPLIES_PAGE = 'SHOW_REPLIES_PAGE'
export const HIDE_REPLIES_PAGE = 'HIDE_REPLIES_PAGE'
export const SHOW_COMMENT_BAR = 'SHOW_COMMENT_BAR'
export const HIDE_COMMENT_BAR = 'HIDE_COMMENT_BAR'
export const SEND_COMMENT_REQ = 'SEND_COMMENT_REQ'
export const SEND_COMMENT_SUC = 'SEND_COMMENT_SUC'
export const SEND_COMMENT_ERR = 'SEND_COMMENT_ERR'

// collect
export const SUC_COLLECT = 'SUC_COLLECT'
export const DEL_COLLECTED = 'DEL_COLLECTED'
// -----